Ext.onReady(function(){
    function btnFunction(btn){
        var value=btn.nvl,comp=Ext.getCmp('exp'),oldValue=comp.getValue();
        numValue=Ext.getCmp('numvalue').getValue();
        
        if(!isNaN(parseInt(value))){
            Ext.getCmp('numvalue').setValue(numValue+value);
        }else{
            Ext.getCmp('numvalue').setValue('');
        }
        if(value=='C'){
            oldValue='';
            value='';
        }
        if(value=='<-'){
             oldValue=oldValue.substring(0,oldValue.length-1);
             value='';
        }
        if(value=='+'||value=='-'||value=='*'||value=="/"||value=="±"){
            if(isNaN(parseInt(oldValue.substring(oldValue.length-1)))){
                value='';
            };
        }
        if(value=='CE'){
            oldValue='';
            value='';
        }
        if(value=='='){
            if(oldValue.trim()==''){
                Ext.MessageBox.alert('警告','请输入数值');
                return;
            }
            value='';
            Ext.Ajax.request({
                url:'calcNum.action',
                method:'post',
                params:{
                    exp:oldValue
                },
                callback:function(options,success,response){
                    if(success){
                        var res=Ext.JSON.decode(response.responseText);
                    Ext.getCmp('result').setValue(res);
                    comp.setValue('');
                    }else{
                         Ext.MessageBox.alert('警告','技术错无'); 
                    }
                }
            })
        }
        /*if(value=='%'){
            value=Number(numValue)/100;
            oldValue=oldValue.replace(numValue,value);
            value='';
        }
        if(value=='1/x'){
            value=1/Number(numValue);
            oldValue=oldValue.replace(numValue,value);
            value='';
        }*/
        
        comp.setValue(oldValue+value);
    }
        Ext.create('Ext.panel.Panel',{
            width:340,
            height:220,
            frame:true,
            renderTo:Ext.getBody(),
            layout: {
                    type: 'table',
                    columns: 5,
                    tdAttrs: {
		            style: {
		                width: '100%',
                        height:'100%'
		            }
                 }
              },
              defaults: {
                 margin:'3px',
                 minWidth:60,
                 handler:btnFunction,
                 xtype:'button',
                 renderTo:Ext.getBody()
             },
            tbar:['表达式',{
                xtype:'textfield',
                width:120,
                readOnly:true,
                id:'exp'
            },{
                xtype:'textfield',
                width:30,
                id:'numvalue'
            },"=",{
                xtype:'numberfield',
                width:120,
                hideTrigger:true,
                readOnly:true,
                id:'result' 
            }],
            items:[{
                    text:'MC',
                    nvl:'MC',
                    disabled:true
                },{
                    text:'MR',
                    nvl:'MR',
                    disabled:true
                },{
                    text:'MS',
                    nvl:'MS',
                    disabled:true
                },{
                    text:'M+',
                    nvl:'M+',
                    disabled:true
                },{
                    text:'M-',
                    nvl:'M-',
                    disabled:true
                },{
                    text:'<-',
                    nvl:'<-'
                },{
                    text:'CE',
                    nvl:'CE'
                },{
                    text:'C',
                    nvl:'C'
                },{
                    text:'±',
                    nvl:'±'
                },{
                    text:'√',
                    nvl:'√' 
                },{
                    text:'7',
                    nvl:'7'
                },{
                    text:'8',
                    nvl:'8'
                },{
                    text:'9',
                    nvl:'9'
                },{
                    text:'/',
                    nvl:'/'
                },{
                    text:'%',
                    nvl:'%' 
                },{
                    text:'4',
                    nvl:'4'
                },{
                    text:'5',
                    nvl:'5'
                },{
                    text:'6',
                    nvl:'6'
                },{
                    text:'*',
                    nvl:'*'
                },{
                    text:'1/x',
                    nvl:'1/x'
                },{
                    text:'1',
                    nvl:'1'
                },{
                    text:'2',
                    nvl:'2'
                },{
                    text:'3',
                    nvl:'3'
                },{
                    text:'-',
                    nvl:'-'
                },{
                    text:'=',
                    nvl:'=',
                    height:51,
                    rowspan:2
                },{
                   text:'0',
                   nvl:'0',
                   width:126,
                   colspan:2
                },{
                   text:'.',
                   nvl:'.'
                },{
                   text:'+',
                   nvl:'+'  
                }]
        })
})